name: budgetapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+13

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^14.2.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6

  intl: ^0.20.2
  flutter_local_notifications: ^19.4.2
  flutter_email_sender: ^8.0.0
  flutter_lints: ^6.0.0
  percent_indicator: ^4.2.3
  pdf: ^3.7.4
  printing: ^5.8.0
  path_provider: ^2.0.9
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.1.6
  package_info_plus: ^8.3.0
  localstore: ^1.2.3
  flutter_screenutil: ^5.4.0+1
  url_launcher: ^6.1.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.0.13
  rxdart: ^0.28.0
  # flutter_native_timezone: ^2.0.0
  overlay_support: ^2.1.0
  provider: ^6.0.2
  google_mobile_ads: ^6.0.0
  currency_picker: ^2.0.9
  pay: ^3.2.1
  flutter_staggered_animations: "^1.0.0"
  animations: ^2.0.2
  introduction_screen: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#48BF84" 
  adaptive_icon_foreground: "assets/icons/icon-monochrome.png"
  adaptive_icon_monochrome: "assets/icons/icon-monochrome.png"

flutter_native_splash:
  background_image: assets/images/splash.png
  image: assets/images/splash_center.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - android/app/src/main/res/drawable-v21/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

