name: budgetapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+16

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
    # generate: true

  cupertino_icons: ^1.0.2
  go_router: ^14.2.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^19.4.2
  flutter_lints: ^6.0.0
  pdf: ^3.7.4
  printing: ^5.8.0
  path_provider: ^2.0.9
  permission_handler: ^12.0.1
  package_info_plus: ^8.3.0
  localstore: ^1.2.3
  flutter_screenutil: ^5.4.0+1
  url_launcher: ^6.1.0
  shared_preferences: ^2.0.13
  flutter_timezone: ^4.1.1
  overlay_support: ^2.1.0
  provider: ^6.0.2
  google_mobile_ads: ^6.0.0
  currency_picker: ^2.0.9
  introduction_screen: ^4.0.0
  equatable: ^2.0.7
  event_bus: ^2.0.1

  flutter_localization: ^0.3.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#48BF84" 
  adaptive_icon_foreground: "assets/icons/icon-monochrome.png"
  adaptive_icon_monochrome: "assets/icons/icon-monochrome.png"

flutter_native_splash:
  color: "#48BF84"
  image: assets/icons/icon-monochrome.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - android/app/src/main/res/drawable-v21/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

